#!/bin/sh
set -e

echo "Post-Installation Macro"

IS_UPGRADE=false

case "$1" in
	configure)
		# Set user permissions
		mkdir -p /opt/geld/webapps/landing-page
		chown -R root:www-data /opt/geld/webapps/landing-page
		chown -R root:www-data /opt/geld/webapps/landing-page
		find /opt/geld/webapps/landing-page -type d -print0 | xargs -0 chmod 755
		find /opt/geld/webapps/landing-page -type f -print0 | xargs -0 chmod 644
		chmod 775 /opt/geld/webapps/landing-page/static/data
		chmod 755 /opt/geld/webapps/landing-page/generate_data.py
		
		# If $1=configure and $2 is set, this is an upgrade
		if [ "$2" != "" ]; then
			IS_UPGRADE=true
		fi
		if [ "$IS_UPGRADE" = "true" ]; then
			echo -n "Restarting service..."
			systemctl daemon-reload
			systemctl restart nginx-landing-page || true
			echo " OK"
			echo -n "Reloading nginx service..."
			sudo service nginx reload
			echo " OK"
		else
			echo -n "Starting service..."
			systemctl daemon-reload
			systemctl enable nginx-landing-page || true
			systemctl start nginx-landing-page || true
			echo " OK"
			echo -n "Reloading nginx service..."
			sudo service nginx reload
			echo " OK"
		fi
		;;
esac
