#!/bin/sh
set -e

echo "Post-Installation Macro"

IS_UPGRADE=false

case "$1" in
	configure)
		# Set user permissions on /opt/geld/webapps/landing-page
		mkdir -p /opt/geld/webapps/landing-page
		chown -R root:www-data /opt/geld/webapps/landing-page
		chmod -R 744 /opt/geld/webapps/landing-page
		# If $1=configure and $2 is set, this is an upgrade
		if [ "$2" != "" ]; then
			IS_UPGRADE=true
		fi
		if [ "$IS_UPGRADE" = "true" ]; then
			echo -n "Restarting service..."
			systemctl daemon-reload
			systemctl restart geldtech-landing-page || true
			echo " OK"
			echo -n "Reloading nginx service..."
			sudo service nginx reload
			echo " OK"
		else
			echo -n "Starting service..."
			systemctl daemon-reload
			systemctl enable geldtech-landing-page || true
			systemctl start geldtech-landing-page || true
			echo " OK"
			echo -n "Reloading nginx service..."
			sudo service nginx reload
			echo " OK"
		fi
		;;
esac
